### ISSUE TITLE
OpenID Fails

### ISSUE THREAD

**Issue by lpcalisi** [stoggi/sshrimp#4]
Hi @stoggi, i am triying to up `sshrimp` but i have some problems. I managed to configure Google OpenID and i got the message `Signed in successfully, return to cli app`, but after it, the agent crash 

```console
sshrimp-agent: listening on /tmp/sshrimp.sock
2020/12/18 00:10:19 <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13e73e6]

goroutine 1 [running]:
golang.org/x/crypto/ssh.(*Certificate).Type(0x0, 0xc00006ae40, 0xc0003ee100)
	/Users/lcalisi/go/pkg/mod/golang.org/x/crypto@v0.0.0-20191128160524-b544559bb6d1/ssh/certs.go:494 +0x26
github.com/stoggi/sshrimp/internal/sshrimpagent.(*sshrimpAgent).List(0xc0001fc700, 0xc000096004, 0x1, 0xc00020f9e0, 0x1091e22, 0xc00008e080)
	/Users/lcalisi/sshrimp/internal/sshrimpagent/sshrimpagent.go:87 +0x18e
golang.org/x/crypto/ssh/agent.(*server).processRequest(0xc00020fbf8, 0xc000096004, 0x1, 0x1, 0xc00020fb70, 0x10719a7, 0xc000094000, 0xc000096004)
	/Users/lcalisi/go/pkg/mod/golang.org/x/crypto@v0.0.0-20191128160524-b544559bb6d1/ssh/agent/server.go:145 +0x5ec
golang.org/x/crypto/ssh/agent.(*server).processRequestBytes(0xc00020fbf8, 0xc000096004, 0x1, 0x1, 0x1, 0x1, 0x1)
	/Users/lcalisi/go/pkg/mod/golang.org/x/crypto@v0.0.0-20191128160524-b544559bb6d1/ssh/agent/server.go:30 +0x67
golang.org/x/crypto/ssh/agent.ServeAgent(0x1875c00, 0xc0001fc700, 0x2d15008, 0xc000094000, 0xc000094000, 0x0)
	/Users/lcalisi/go/pkg/mod/golang.org/x/crypto@v0.0.0-20191128160524-b544559bb6d1/ssh/agent/server.go:557 +0x1c6
main.launchAgent(0xc0002c65a0, 0xc0001fc100, 0x0, 0x0)
	/Users/lcalisi/sshrimp/cmd/sshrimp-agent/main.go:88 +0x537
main.main()
	/Users/lcalisi/sshrimp/cmd/sshrimp-agent/main.go:37 +0x4a5
```

How i need to config the OpenID? Additionally, i have another question, how i could get aws credentials to invoke shrimp lambda function through OpenID? Do i need use the `aws-oidc` ?

My `sshrimp.toml` looks:

```config
[Agent]
  ProviderURL = "https://accounts.google.com"
  ClientID = "CLIENT_ID"
  ClientSecret = "CLIENT_SECRET"
  BrowserCommand = ["open", "-a", "Google Chrome", "{}"]
  Socket = "/tmp/sshrimp.sock"

[CertificateAuthority]
  AccountID = AWS_ACCOUNT_ID
  Regions = ["us-east-1"]
  FunctionName = "sshrimp"
  KeyAlias = "alias/sshrimp"
  ForceCommandRegex = "^$"
  SourceAddressRegex = "^$"
  UsernameRegex = "^(.*)@example\\.com$"
  UsernameClaim = "email"
  ValidAfterOffset = "-5m"
  ValidBeforeOffset = "+12h"
  Extensions = ["no-x11-forwarding", "permit-agent-forwarding", "permit-port-forwarding", "permit-pty", "permit-user-rc"]
```

**Comment by stoggi** [comment]
Hello @lpcalisi,

Sorry the error handling isn't great there, I think you need to call `sshrimp-agent /path/to/sshrimp.toml` with valid AWS credentials that have permission to invoke the sshrimp lambda.

You could create a test IAM user and only grant it permission to `lambda:InvokeFunction`, and put the credentials in your `~/.aws/credentials` file or use something like [aws-vault](https://github.com/99designs/aws-vault) to assume a role.

**Comment by lpcalisi** [comment]
Hi @stoggi , i had tried with assumed rol in the terminal that the agent run (and in the `ssh` too) but the error is the same

**Comment by stoggi** [comment]
@lpcalisi , hm and you deployed the sshrimp lambda with `terraform init` then `terraform apply`?

I'm pretty sure that error is that no certificate was returned, or an error while invoking the lambda function.

**Comment by lpcalisi** [comment]
Hi @stoggi , i have been debug the agent and i think that the problem is in `AssumeRolWithWebIdentity` , the JWT is getted from `https://accounts.google.com` but not the AWS creds, then when `sshrimp-agent` call to sign certificate fails because dont have credentials. Do not i need specify RolARN for `aws-oidc` that make the assume rol?

**Comment by gazzenger** [comment]
Hello, 

I stumbled across this repository, and wanted to give it a try.
I've gone through the instructions, and setup an app registration with AzureAD.

It authenticates the user successfully, but shows the same error.

@lpcalisi did you have any luck in finding your issue?

**Comment by stoggi** [comment]
@gazzenger I think you don't have any configured credentials when invoking the lambda function to sign your certificate.

https://github.com/stoggi/sshrimp/blob/6c3e3ad9126370e6b3523ea3eea94f7658ab9b41/internal/signer/sshrimp.go#L47-L50

This bit of code does not yet use AssumeRoleWithWebIdentity like @lpcalisi suggests, although you could do that. It rather leaves you to set up your AWS credentials separately in your environment.

**Comment by gazzenger** [comment]
Fantastic I managed to get it to work.
Many thanks

**Comment by stoggi** [comment]
Awesome!

If there are particular features you need or bugs you find, feel free to
open an issue.
