### ISSUE TITLE
Read Unix Socket

### ISSUE THREAD

**Issue by lpcalisi** [stoggi/sshrimp#5]
Hi @stoggi , it is possible get ssh connection data in the agent?

For example.. if i make a connection like `ssh ubuntu@host`, is it possible that the agent receives this data? if true, maybe we can sign specific certificates for each host and maybe forcing commands o other features.

Thanks you!

**Comment by stoggi** [comment]
Hmm this is a good question. I'm not sure if you get access to the hostname in tbe ssh agent protocol, but you might be use a host certificate, and encode that information there, and use it to sign your client certificate. I'll give this a go.
